# Generated by Django 3.2.8 on 2021-11-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='specialized_in',
            field=models.TextField(blank=True, null=True),
        ),
    ]
