# Generated by Django 3.2.8 on 2021-11-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_alter_employee_specialized_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
