# Generated by Django 3.2.8 on 2021-11-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_auto_20211119_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
